#!/bin/bash
# LWS Backup v10
# Backup + Restore Kit Builder

VERSION="10"
LWS_ROOT="/LWS_Backup"

SCRIPT_DIR="$LWS_ROOT/scripts"
BACKUP_DIR="$LWS_ROOT/backups"
RESTORE_KIT_DIR="$LWS_ROOT/restore_kits"
LOG_DIR="$LWS_ROOT/logs"
TMP_DIR="$LWS_ROOT/tmp"

DATESTAMP="$(date +%Y%m%d-%H%M%S)"
HOSTNAME="$(hostname)"

BACKUP_NAME="Backup_${HOSTNAME}_${DATESTAMP}.zip"
RESTORE_KIT_NAME="Restore_kit_${HOSTNAME}_${DATESTAMP}.zip"

BACKUP_FILE="$BACKUP_DIR/$BACKUP_NAME"
LATEST_BACKUP_FILE="$BACKUP_DIR/Backup_latest.zip"

RESTORE_KIT_FILE="$RESTORE_KIT_DIR/$RESTORE_KIT_NAME"
LATEST_RESTORE_KIT_FILE="$RESTORE_KIT_DIR/Restore_kit_latest.zip"

LOG_FILE="$LOG_DIR/backup_v10_${DATESTAMP}.log"

WORK_DIR="$TMP_DIR/work_${DATESTAMP}"
KIT_DIR="$TMP_DIR/Restore_kit_${DATESTAMP}"

SELF_SCRIPT="$SCRIPT_DIR/backup_v10.sh"
MAX_BACKUPS=2
MAX_RESTORE_KITS=2

echo_log() {
    echo "$1"
    echo "$(date '+%Y-%m-%d %H:%M:%S') - $1" >> "$LOG_FILE"
}

cleanup() {
    rm -rf "$WORK_DIR" "$KIT_DIR"
}

fail_exit() {
    echo_log "ERROR: $1"
    cleanup
    exit 1
}

check_root() {
    if [ "$(id -u)" != "0" ]; then
        echo "This script must be run as root."
        exit 1
    fi
}

create_folders() {
    mkdir -p "$SCRIPT_DIR" "$BACKUP_DIR" "$RESTORE_KIT_DIR" "$LOG_DIR" "$TMP_DIR"
}

check_command() {
    command_name="$1"

    if ! command -v "$command_name" >/dev/null 2>&1; then
        echo "$command_name is missing. Attempting to install..."

        if command -v apt-get >/dev/null 2>&1; then
            apt-get update -qq && apt-get install -y "$command_name"
        elif command -v yum >/dev/null 2>&1; then
            yum install -y "$command_name"
        elif command -v pacman >/dev/null 2>&1; then
            pacman -Sy --noconfirm "$command_name"
        else
            fail_exit "No supported package manager found. Install $command_name manually."
        fi

        if ! command -v "$command_name" >/dev/null 2>&1; then
            fail_exit "Installation of $command_name failed."
        fi
    fi
}

check_commands() {
    check_command zip
    check_command unzip
    check_command sha256sum
}

backup_original_targets() {
    echo_log "Creating backup workspace..."
    mkdir -p "$WORK_DIR"

    echo_log "Collecting original backup targets..."

    if [ -d "/srv/http" ]; then
        cp -a /srv/http "$WORK_DIR/HTTP" || fail_exit "Failed copying /srv/http"
        echo_log "Added: /srv/http"
    else
        echo_log "Skipped missing: /srv/http"
    fi

    if [ -d "/etc/asterisk" ]; then
        cp -a /etc/asterisk "$WORK_DIR/Asterisk" || fail_exit "Failed copying /etc/asterisk"
        echo_log "Added: /etc/asterisk"
    else
        echo_log "Skipped missing: /etc/asterisk"
    fi

    if [ -f "/var/spool/cron/root" ]; then
        cp -a /var/spool/cron/root "$WORK_DIR/root" || fail_exit "Failed copying /var/spool/cron/root"
        echo_log "Added: /var/spool/cron/root"
    else
        echo_log "Skipped missing: /var/spool/cron/root"
    fi
}

create_backup() {
    backup_original_targets

    echo_log "Creating backup zip: $BACKUP_FILE"

    (
        cd "$WORK_DIR" || exit 1
        zip -r "$BACKUP_FILE" ./*
    ) >> "$LOG_FILE" 2>&1 || fail_exit "Backup zip failed"

    cp -f "$BACKUP_FILE" "$LATEST_BACKUP_FILE"

    echo_log "Backup created successfully."
}

create_restore_script() {
    cat > "$KIT_DIR/restore.sh" <<'EOF'
#!/bin/bash
# Restore Script generated by LWS Backup v10

KIT_DIR="$(cd "$(dirname "$0")" && pwd)"
BACKUP_ZIP="$KIT_DIR/backups/Backup_latest.zip"
RESTORE_WORK="/tmp/Restore_work_$$"
LOG_FILE="$KIT_DIR/restore.log"

echo_log() {
    echo "$1"
    echo "$(date '+%Y-%m-%d %H:%M:%S') - $1" >> "$LOG_FILE"
}

fail_exit() {
    echo_log "ERROR: $1"
    rm -rf "$RESTORE_WORK"
    exit 1
}

if [ "$(id -u)" != "0" ]; then
    echo "This restore script must be run as root."
    exit 1
fi

echo_log "Starting restore..."

command -v unzip >/dev/null 2>&1 || fail_exit "unzip is missing"
command -v cp >/dev/null 2>&1 || fail_exit "cp is missing"

if [ ! -f "$BACKUP_ZIP" ]; then
    fail_exit "Backup zip not found: $BACKUP_ZIP"
fi

mkdir -p "$RESTORE_WORK"

echo_log "Extracting backup..."
unzip -q "$BACKUP_ZIP" -d "$RESTORE_WORK" || fail_exit "Could not unzip backup"

if [ -d "$RESTORE_WORK/HTTP" ]; then
    mkdir -p /srv/http
    cp -a "$RESTORE_WORK/HTTP/." /srv/http/ || fail_exit "Failed restoring /srv/http"
    echo_log "Restored: /srv/http"
fi

if [ -d "$RESTORE_WORK/Asterisk" ]; then
    mkdir -p /etc/asterisk
    cp -a "$RESTORE_WORK/Asterisk/." /etc/asterisk/ || fail_exit "Failed restoring /etc/asterisk"
    echo_log "Restored: /etc/asterisk"
fi

if [ -f "$RESTORE_WORK/root" ]; then
    mkdir -p /var/spool/cron
    cp -a "$RESTORE_WORK/root" /var/spool/cron/root || fail_exit "Failed restoring /var/spool/cron/root"
    echo_log "Restored: /var/spool/cron/root"
fi

chmod +x /LWS_Backup/scripts/*.sh 2>/dev/null

echo_log "Restore completed."

echo
echo "Restore completed."
echo "Reboot recommended:"
echo
echo "reboot"
echo

rm -rf "$RESTORE_WORK"
exit 0
EOF

    chmod +x "$KIT_DIR/restore.sh"
}

create_restore_config() {
    cat > "$KIT_DIR/restore_config.conf" <<EOF
VERSION="$VERSION"
HOSTNAME="$HOSTNAME"
CREATED="$DATESTAMP"
BACKUP_FILE="backups/Backup_latest.zip"

RESTORE_HTTP="/srv/http"
RESTORE_ASTERISK="/etc/asterisk"
RESTORE_CRON_ROOT="/var/spool/cron/root"
EOF
}

create_readme() {
    cat > "$KIT_DIR/README_RESTORE.txt" <<EOF
Restore Kit
Created: $DATESTAMP
Host: $HOSTNAME

Restore instructions:

1. Unzip:
   unzip Restore_kit_latest.zip

2. Enter folder:
   cd Restore_kit

3. Run:
   ./restore.sh

4. Reboot:
   reboot

This kit restores:
- /srv/http
- /etc/asterisk
- /var/spool/cron/root
EOF
}

create_restore_kit() {
    echo_log "Creating restore kit..."

    mkdir -p "$KIT_DIR/backups"
    mkdir -p "$KIT_DIR/scripts"

    cp -f "$LATEST_BACKUP_FILE" "$KIT_DIR/backups/Backup_latest.zip"
    cp -f "$SELF_SCRIPT" "$KIT_DIR/scripts/backup_v10.sh" 2>/dev/null || cp -f "$0" "$KIT_DIR/scripts/backup_v10.sh"

    create_restore_script
    create_restore_config
    create_readme

    (
        cd "$KIT_DIR" || exit 1
        sha256sum backups/Backup_latest.zip > sha256sums.txt
    ) >> "$LOG_FILE" 2>&1

    echo_log "Zipping restore kit: $RESTORE_KIT_FILE"

    (
        cd "$TMP_DIR" || exit 1
        mv "$KIT_DIR" "$TMP_DIR/Restore_kit"
        zip -r "$RESTORE_KIT_FILE" "Restore_kit"
    ) >> "$LOG_FILE" 2>&1 || fail_exit "Restore kit zip failed"

    cp -f "$RESTORE_KIT_FILE" "$LATEST_RESTORE_KIT_FILE"

    echo_log "Restore kit created successfully."
}

cleanup_old_files() {
    find "$BACKUP_DIR" -name "Backup_*.zip" -type f | sort | head -n -"$MAX_BACKUPS" | xargs -r rm --
    find "$RESTORE_KIT_DIR" -name "Restore_kit_*.zip" -type f | sort | head -n -"$MAX_RESTORE_KITS" | xargs -r rm --
}

create_symlinks() {
    ln -sf "$SELF_SCRIPT" /usr/local/sbin/lws-backup
    echo_log "Symlink created: /usr/local/sbin/lws-backup"
}

main() {
    check_root
    create_folders
    check_commands

    echo_log "Starting LWS Backup v$VERSION"

    create_backup
    create_restore_kit
    cleanup_old_files
    create_symlinks
    cleanup

    echo_log "Backup job completed."

    echo
    echo "Backup complete."
    echo "Backup: $BACKUP_FILE"
    echo "Restore kit: $RESTORE_KIT_FILE"
    echo "Latest backup: $LATEST_BACKUP_FILE"
    echo "Latest restore kit: $LATEST_RESTORE_KIT_FILE"
    echo
}

main "$@"