#!/bin/bash
# Restore Script generated by LWSBackup v@LWS_VERSION@
KIT_DIR="$(cd "$(dirname "$0")" && pwd)"
BACKUP_ZIP="$KIT_DIR/@KIT_BACKUP_PATH@"
TARGETS_FILE="$KIT_DIR/restore_targets.conf"
RESTORE_WORK="/tmp/LWSBackup_restore_work_$$"
LOG_FILE="$KIT_DIR/restore.log"
DRY_RUN="no"
LWS_ROOT="@LWS_ROOT@"

echo_log() { echo "$1"; echo "$(date '+%Y-%m-%d %H:%M:%S') - $1" >> "$LOG_FILE"; }
fail_exit() { echo_log "ERROR: $1"; rm -rf "$RESTORE_WORK"; exit 1; }
usage() { echo "Usage: sudo ./restore.sh [--dry-run]"; }
[ "$1" = "--dry-run" ] && DRY_RUN="yes"
[ "$1" = "--help" ] || [ "$1" = "-h" ] && { usage; exit 0; }
[ "$(id -u)" != "0" ] && { echo "This restore script must be run as root."; exit 1; }
command -v unzip >/dev/null 2>&1 || fail_exit "unzip is missing"
command -v cp >/dev/null 2>&1 || fail_exit "cp is missing"
[ -f "$BACKUP_ZIP" ] || fail_exit "Backup zip not found: $BACKUP_ZIP"
[ -f "$TARGETS_FILE" ] || fail_exit "Restore target file not found: $TARGETS_FILE"
echo_log "Starting restore..."
[ "$DRY_RUN" = "yes" ] && echo_log "DRY RUN MODE: No files will be changed."
mkdir -p "$RESTORE_WORK"
unzip -q "$BACKUP_ZIP" -d "$RESTORE_WORK" || fail_exit "Could not unzip backup"
backup_existing_path() {
    dest="$1"
    if [ -e "$dest" ]; then
        bak="${dest}.bak.$(date +%Y%m%d-%H%M%S)"
        echo_log "Existing path found: $dest"
        echo_log "Creating safety backup: $bak"
        [ "$DRY_RUN" = "no" ] && cp -a "$dest" "$bak" || true
    fi
}
restore_dir() {
    zipname="$1"; dest="$2"; src="$RESTORE_WORK/$zipname"
    [ -d "$src" ] || { echo_log "Skipped missing ZIP directory: $zipname"; return; }
    echo_log "Restore directory: $zipname -> $dest"
    backup_existing_path "$dest"
    if [ "$DRY_RUN" = "no" ]; then
        mkdir -p "$dest" || fail_exit "Could not create $dest"
        cp -a "$src/." "$dest/" || fail_exit "Failed restoring $dest"
    fi
}
restore_file() {
    zipname="$1"; dest="$2"; src="$RESTORE_WORK/$zipname"
    [ -f "$src" ] || { echo_log "Skipped missing ZIP file: $zipname"; return; }
    echo_log "Restore file: $zipname -> $dest"
    backup_existing_path "$dest"
    if [ "$DRY_RUN" = "no" ]; then
        mkdir -p "$(dirname "$dest")" || fail_exit "Could not create parent folder for $dest"
        cp -a "$src" "$dest" || fail_exit "Failed restoring $dest"
    fi
}
while IFS='|' read -r type src zipname dest; do
    case "$type" in
        ""|\#*) continue ;;
    esac
    [ -z "$dest" ] && dest="$src"
    [ "$type" = "DIR" ] && restore_dir "$zipname" "$dest"
    [ "$type" = "FILE" ] && restore_file "$zipname" "$dest"
done < "$TARGETS_FILE"
chmod +x "$LWS_ROOT/scripts/"*.sh 2>/dev/null
if [ "$DRY_RUN" = "yes" ]; then
    echo_log "Dry-run restore completed. No files were changed."
else
    echo_log "Restore completed. Reboot recommended."
fi
rm -rf "$RESTORE_WORK"
exit 0
