# LWSBackup archive naming
build_names() {
    BACKUP_NAME="${BACKUP_PREFIX}_${HOSTNAME}_${DATESTAMP}.zip"
    RESTORE_KIT_NAME="${RESTORE_KIT_PREFIX}_${HOSTNAME}_${DATESTAMP}.zip"
    BACKUP_FILE="$BACKUP_DIR/$BACKUP_NAME"
    LATEST_BACKUP_NAME="${BACKUP_PREFIX}_latest.zip"
    LATEST_BACKUP_FILE="$BACKUP_DIR/$LATEST_BACKUP_NAME"
    RESTORE_KIT_FILE="$RESTORE_KIT_DIR/$RESTORE_KIT_NAME"
    LATEST_RESTORE_KIT_NAME="${RESTORE_KIT_PREFIX}_latest.zip"
    LATEST_RESTORE_KIT_FILE="$RESTORE_KIT_DIR/$LATEST_RESTORE_KIT_NAME"
    KIT_BACKUP_PATH="backups/$LATEST_BACKUP_NAME"
    KIT_FOLDER_NAME="${RESTORE_KIT_PREFIX}"
}
