# LWSBackup restore kit builder

create_restore_script() {
    template="${LWS_SCRIPT_ROOT}/templates/restore.sh"
    [ -f "$template" ] || fail_exit "Restore template missing: $template"
    sed \
        -e "s|@LWS_VERSION@|${VERSION}|g" \
        -e "s|@KIT_BACKUP_PATH@|${KIT_BACKUP_PATH}|g" \
        -e "s|@LWS_ROOT@|${LWS_ROOT}|g" \
        "$template" > "$KIT_DIR/restore.sh"
    chmod +x "$KIT_DIR/restore.sh"
}

create_restore_kit() {
    build_names
    echo_log "Creating restore kit..."
    mkdir -p "$KIT_DIR/backups" "$KIT_DIR/scripts" || fail_exit "Could not create restore kit folders"
    cp -f "$LATEST_BACKUP_FILE" "$KIT_DIR/$KIT_BACKUP_PATH" || fail_exit "Could not copy latest backup into restore kit"
    cp -f "$TARGETS_FILE" "$KIT_DIR/restore_targets.conf" || fail_exit "Could not copy targets file into restore kit"
    mkdir -p "$KIT_DIR/scripts/lib" "$KIT_DIR/scripts/ui" "$KIT_DIR/scripts/templates" "$KIT_DIR/scripts/commands"
    cp -f "$LWS_SCRIPT_ROOT/lws-backup" "$KIT_DIR/scripts/lws-backup" 2>/dev/null || cp -f "$0" "$KIT_DIR/scripts/lws-backup"
    chmod +x "$KIT_DIR/scripts/lws-backup"
    for subdir in lib ui templates commands; do
        if [ -d "$LWS_SCRIPT_ROOT/$subdir" ]; then
            cp -a "$LWS_SCRIPT_ROOT/$subdir/." "$KIT_DIR/scripts/$subdir/" 2>/dev/null
        fi
    done
    cat > "$KIT_DIR/scripts/lwsbackup.sh" <<'EOW'
#!/bin/bash
exec "$(cd "$(dirname "$0")" && pwd)/lws-backup" "$@"
EOW
    chmod +x "$KIT_DIR/scripts/lwsbackup.sh"
    create_restore_script
    cat > "$KIT_DIR/restore_config.conf" <<EOC
VERSION="$VERSION"
HOSTNAME="$HOSTNAME"
CREATED="$DATESTAMP"
BACKUP_FILE="$KIT_BACKUP_PATH"
TARGETS_FILE="restore_targets.conf"
EOC
    cat > "$KIT_DIR/README_RESTORE.txt" <<EOR
LWSBackup Restore Kit
Created: $DATESTAMP
Host: $HOSTNAME
Generated by: LWSBackup v$VERSION

Restore instructions:
1. unzip $LATEST_RESTORE_KIT_NAME
2. cd $KIT_FOLDER_NAME
3. sudo ./restore.sh --dry-run
4. sudo ./restore.sh
5. sudo reboot

Existing restore destinations are copied to .bak.YYYYMMDD-HHMMSS before overwrite.
EOR
    ( cd "$KIT_DIR" || exit 1; sha256sum "$KIT_BACKUP_PATH" > sha256sums.txt ) >> "$LOG_FILE" 2>&1
    echo_log "Zipping restore kit: $RESTORE_KIT_FILE"
    ( cd "$TMP_DIR" || exit 1
      rm -rf "$TMP_DIR/$KIT_FOLDER_NAME"
      mv "$KIT_DIR" "$TMP_DIR/$KIT_FOLDER_NAME"
      zip -r "$RESTORE_KIT_FILE" "$KIT_FOLDER_NAME"
    ) >> "$LOG_FILE" 2>&1 || fail_exit "Restore kit zip failed"
    cp -f "$RESTORE_KIT_FILE" "$LATEST_RESTORE_KIT_FILE" || fail_exit "Could not update latest restore kit"
    echo_log "Restore kit created successfully."
}
